apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Data
  sourceRepos:
  - '*'
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: prod
    server: https://kubernetes.default.svc
  roles:
  - name: prod-role
    description: Sync privileges on prod apps
    policies:
    - p, proj:prod:prod-role, applications, sync, prod/*, allow
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
