# Secret to add this repository
apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/javirugo/argocd-homelab.git


---
# Secret to add the apps repository
apiVersion: v1
kind: Secret
metadata:
  name: github-apps
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/javirugo/argocd-applications.git


---
# Main project "argocd"
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: ArgoCD Apps
  sourceRepos:
  - '*'
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: cert-manager
    server: https://kubernetes.default.svc
  - namespace: default
    server: https://kubernetes.default.svc
  - namespace: dev
    server: https://kubernetes.default.svc
  - namespace: prod
    server: https://kubernetes.default.svc
  roles:
  - name: argocd-role
    description: Sync privileges on argocd apps
    policies:
    - p, proj:argocd:argocd-role, applications, sync, argocd/*, allow
    - p, proj:argocd:argocd-role, applications, sync, cert-manager/*, allow
    - p, proj:argocd:argocd-role, applications, sync, default/*, allow
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'



---
# ArgoCD K8S
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 0-apps-k8s
  namespace: argocd
spec:
  project: argocd
  source:
    repoURL: https://github.com/javirugo/argocd-homelab.git
    targetRevision: main
    path: k8s-objects
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}


---
# ArgoCD projects
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 0-apps-argocd
  namespace: argocd
spec:
  project: argocd
  source:
    repoURL: https://github.com/javirugo/argocd-homelab.git
    targetRevision: main
    path: projects
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}


---
# Application of all applications
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 0-apps-all
  namespace: argocd
spec:
  project: argocd
  source:
    repoURL: https://github.com/javirugo/argocd-homelab.git
    targetRevision: main
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}

