# Application of all applications
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 0-apps-prod
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: https://github.com/javirugo/argocd-applications.git
    targetRevision: main
    path: prod/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated: {}
