# Application of all applications
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 0-apps-build
  namespace: argocd
spec:
  project: argocd
  source:
    repoURL: https://github.com/javirugo/argocd-homelab.git
    targetRevision: main
    path: apps/build
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
